suite: Metrics secret template (monitoring disabled)
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/gitea/metrics-secret.yaml
tests:
  - it: renders nothing if monitoring disabled and gitea.metrics.token empty
    set:
      gitea.metrics.enabled: false
      gitea.metrics.serviceMonitor.enabled: false
      gitea.metrics.token: ""
    asserts:
      - hasDocuments:
          count: 0
  - it: renders nothing if monitoring disabled and gitea.metrics.token not empty
    set:
      gitea.metrics.enabled: false
      gitea.metrics.serviceMonitor.enabled: false
      gitea.metrics.token: "test-token"
    asserts:
      - hasDocuments:
          count: 0
