suite: deployment template (basic)
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/gitea/deployment.yaml
  - templates/gitea/config.yaml
tests:
  - it: renders a deployment
    template: templates/gitea/deployment.yaml
    asserts:
      - hasDocuments:
          count: 1
      - containsDocument:
          kind: Deployment
          apiVersion: apps/v1
          name: gitea-unittests
  - it: deployment labels are set
    template: templates/gitea/deployment.yaml
    set:
      deployment.labels:
        hello: world
    asserts:
      - isSubset:
          path: metadata.labels
          content:
            hello: world
      - isSubset:
          path: spec.template.metadata.labels
          content:
            hello: world
