suite: actions template | job
release:
  name: gitea-unittests
  namespace: testing
chart:
  # Override appVersion to have a pinned version for comparison
  appVersion: 1.19.3
templates:
  - templates/gitea/act_runner/job.yaml
tests:
  - it: renders a Job
    template: templates/gitea/act_runner/job.yaml
    set:
      actions:
        enabled: true
        provisioning:
          enabled: true
      persistence:
        enabled: true
        mount: true
    asserts:
      - hasDocuments:
          count: 1
      - containsDocument:
          kind: Job
          apiVersion: batch/v1
          name: gitea-unittests-actions-token-job
      - equal:
          path: spec.template.spec.containers[0].image
          value: "gitea/gitea:1.19.3-rootless"
  - it: tag override
    template: templates/gitea/act_runner/job.yaml
    set:
      image.tag: "1.19.4"
      actions:
        enabled: true
        provisioning:
          enabled: true
          publish:
            tag: "1.29.0"
      persistence:
        enabled: true
        mount: true
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: "gitea/gitea:1.19.4-rootless"
      - equal:
          path: spec.template.spec.containers[1].image
          value: "bitnami/kubectl:1.29.0"
  - it: doesn't renders a Job by default
    template: templates/gitea/act_runner/job.yaml
    asserts:
      - hasDocuments:
          count: 0
  - it: doesn't renders a Job when provisioning is enabled BUT actions are not enabled
    template: templates/gitea/act_runner/job.yaml
    set:
      actions:
        enabled: false
        provisioning:
          enabled: true
    asserts:
      - hasDocuments:
          count: 0
